server:
  port: 6001
spring:
  application:
    name: boot_mq_producer
  activemq:
    #broker-url: tcp://192.168.146.128:61616 #ActiveMQ服务器IP
    #broker-url: nio://192.168.146.128:61618
    broker-url: tcp://192.168.146.128:61608 #auto+nio
    #broker-url: failover:(tcp://192.168.146.128:61608,tcp://192.168.146.129:61608)
    user: admin #ActiveMQ连接用户名
    password: admin #ActiveMQ连接密码
    
  jms:
    #指定连接队列还是主题
    pub-sub-domain: true # false = Queue |  true = Topic
    template:
      delivery-mode: persistent #持久化
    

#定义服务上的队列名
myQueueName: springboot-activemq-queue-jdbc
myTopicName: springboot-activemq-topic-jdbc

